apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiu-test
  namespace: argocd
  finalizers: null
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=docker.io/nginx:latest,redis=docker.io/redis:latest
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-repository: git@github.com:onesb23/aiu-demo.git
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:./values/images.yaml"
    argocd-image-updater.argoproj.io/nginx.helm.image-name: nginx.image.name
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: nginx.image.tag
    argocd-image-updater.argoproj.io/redis.helm.image-name: redis.image.name
    argocd-image-updater.argoproj.io/redis.helm.image-tag: redis.image.tag
spec:
  project: default
  sources:
  - repoURL: https://github.com/onesb23/aiu-demo
    targetRevision: HEAD
    path: helm/
    helm:
      valueFiles:
      - values/nginx.yaml
      - values/images.yaml
  - repoURL: https://github.com/onesb23/aiu-demo
    targetRevision: HEAD
    path: helm/
    helm:
      valueFiles:
      - values/redis.yaml
      - values/images.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  info:
  - name: 'Git path'
    value: 'https://github.com/onesb23/aiu-demo'
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: true
#    syncOptions:
#    - Validate=true
#    - CreateNamespace=true
#    - PrunePropagationPolicy=foreground
#    - PruneLast=true
#    - RespectIgnoreDifferences=true
#    - ApplyOutOfSyncOnly=true
#    retry:
#      limit: 3
#      backoff:
#        duration: 5s
#        factor: 2
#        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /metadata/labels
    - /spec/replicas
  revisionHistoryLimit: 10
