apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.nameOverride }}-gamma
  labels:
    app: test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          {{- with (index .Values "myName") }}
          image: "{{ .image.name }}:{{ .image.tag }}"
          {{- end }}
